---
name: "sparc2-plugin-sidebar"
controllers:
  - SPARCControllerSidebar.js
  - SPARCControllerModalLayer.js
directives:
  - sparcSidebar.js
  - sparcSidebarFeatureLayer.js
  - sparcModalFilterMore.js
  - sparcFilterCheckbox.js
  - sparcFilterRadio.js
  - sparcFilterSlider.js
  - sparcModalLayer.js
templates:
  - sparc_sidebar.tpl.html
  - sparc_sidebar_featurelayer.tpl.html
  - filter/filter_checkbox.tpl.html
  - filter/filter_radio.tpl.html
  - filter/filter_slider.tpl.html
  - modal/sparc_modal_layer.tpl.html
less:
  - sidebar.less
  - sidebar-toggle.less
  - filter.less
modals:
  - name: sparc_modal_layer
    ui:
      mainClass: ""
      tabs:
        - target: sparc-modal-layer-general
          label: General
        - target: sparc-modal-layer-attributes
          label: Attributes
        - target: sparc-modal-layer-source
          label: Source
        - target: sparc-modal-layer-download
          label: Download
        - target: sparc-modal-layer-links
          label: Links
